on:
  release:
    types:
      - published

name: Release
jobs:
  release:
    name: Release GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - name: Semver release
        uses: technote-space/release-github-actions@v7.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
